# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/l3853/Documents/TCSS600/FPGA_projects/FPGA_projects/bram_image_process/bram_image_process.srcs/sources_1/ip/bram_image/bram_image.xci
# IP: The module: 'bram_image' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/l3853/Documents/TCSS600/FPGA_projects/FPGA_projects/bram_image_process/bram_image_process.gen/sources_1/ip/bram_image/bram_image_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_image'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/l3853/Documents/TCSS600/FPGA_projects/FPGA_projects/bram_image_process/bram_image_process.srcs/sources_1/ip/bram_image/bram_image.xci
# IP: The module: 'bram_image' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/l3853/Documents/TCSS600/FPGA_projects/FPGA_projects/bram_image_process/bram_image_process.gen/sources_1/ip/bram_image/bram_image_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_image'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
