# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/l3853/Documents/GitHub/FPGA/image_runtime_test/image_runtime_test.srcs/sources_1/ip/bram_image/bram_image.xci
# IP: The module: 'bram_image' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/l3853/Documents/GitHub/FPGA/image_runtime_test/image_runtime_test.gen/sources_1/ip/bram_image/bram_image_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_image'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/l3853/Documents/GitHub/FPGA/image_runtime_test/image_runtime_test.srcs/sources_1/ip/bram_image/bram_image.xci
# IP: The module: 'bram_image' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/l3853/Documents/GitHub/FPGA/image_runtime_test/image_runtime_test.gen/sources_1/ip/bram_image/bram_image_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_image'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
